name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions: {}

env:
  NEXTEST_PROFILE: ci

jobs:
  determine_changes:
    name: "determine changes"
    runs-on: ubuntu-latest
    outputs:
      code: ${{ steps.check_code.outputs.changed }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Determine merge base
        id: merge_base
        env:
          BASE_REF: ${{ github.event.pull_request.base.ref || 'main' }}
        run: |
          sha=$(git merge-base HEAD "origin/${BASE_REF}")
          echo "sha=${sha}" >> "$GITHUB_OUTPUT"

      - name: Check if there was any code related change
        id: check_code
        env:
          MERGE_BASE: ${{ steps.merge_base.outputs.sha }}
        run: |
          if git diff --quiet "${MERGE_BASE}...HEAD" -- \
            . \
            ':!docs/' \
            ':!.markdownlint.yaml' \
            ':!.pre-commit-config.yaml' \
            ':!CHANGELOG.md' \
            ':!CONTRIBUTING.md' \
            ':!LICENSE' \
            ':!README.md' \
          ; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

  pre-commit:
    name: "pre commit"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: j178/prek-action@91fd7d7cf70ae1dee9f4f44e7dfa5d1073fe6623 # v1.0.11

  cargo-test:
    name: "cargo test (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}
    needs: determine_changes
    if: ${{ (needs.determine_changes.outputs.code == 'true' || github.ref == 'refs/heads/main') }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Install Rust toolchain
        run: rustup show

      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2

      - name: Install cargo-nextest
        uses: taiki-e/install-action@a416ddeedbd372e614cc1386e8b642692f66865e # v2.57.1
        with:
          tool: cargo-nextest

      - name: Run tests
        run: cargo nextest run
